# Generated by Django 4.0.4 on 2022-05-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
